### ISSUE TITLE
Provide more useful examples in the notebook

### ISSUE THREAD

**Issue by wenzeslaus** [ncsu-landscape-dynamics/pathways-simulation#45]
The notebook currently contains an example from a test, so perhaps not that useful.

Given that only limited number of characters can be shown for stems with `--pretty`, it would be good to have two examples or two sets of examples, one small to show distribution of pests and another full size but without `--pretty`.

Possibly, `--pretty boxes_only` could help too since it shows only boxes, i.e., much lower number of characters, but it still be a lot if somebody creates a large simulation. So, solving it with two examples may avoid some surprises and it is a good opportunity to explain the issue with a lot of output (less of an issue in command line, but still an issue at some point).

**Comment by kellynm** [comment]
Ok, sure! That sounds great.
