### ISSUE TITLE
Remove --pretty flag from simulation in notebook.

### ISSUE THREAD

**Issue by kellynm** [ncsu-landscape-dynamics/pathways-simulation#48]

**Comment by wenzeslaus** [comment]
See also #45 for an alternative approach.

**Comment by kellynm** [comment]
Is #45 doable within a day or two, before we send out the email with the notebook link?

**Comment by wenzeslaus** [comment]
I think so if the number of examples is limited, e.g., just one with `--pretty` and another without.

**Comment by kellynm** [comment]
Ok, closing this one in favor of #45.
