### ISSUE TITLE
Do not return simulation parameters from the simulation

### ISSUE THREAD

**Issue by wenzeslaus** [ncsu-landscape-dynamics/pathways-simulation#49]
In Python, the caller of simulation already knows the parameters the simulation was called with. Where it is needed is command line or other user-focused outputs where the context is possibly lost and user desired something along the lines of a report.

Ideally, a separate function in outputs.py would take care of printing of the config and this function can be used in app.py and potentially reused when running simulation directly from Python.

Python has a handy, although little unexpected syntax, for printing variables in the dictionary which we could use here to make the code succinct:

```
# assuming we have `config` now
# basic usage
"Max is {config[shipments][max]}".format(config=config)
# if variable names are matching, we can use (basically the new f-strings but working in older Python versions), already used in the code a lot:
"Max is {config[shipments][max]}".format(**locals())
# or reduce the nesting to get shorter references within the strings
"Max is {shipments[max]}".format(shipments=config["shipments"])
```

This should also get us closer to fixing the tests and code checks again.

**Comment by kellynm** [comment]
I knew there was a better way to do this, but wanted to get it working for demonstration today. I will not have time to work on this improvement before sending email with notebook link.
