### ISSUE TITLE
Split add_contaminant_clusters into two functions

### ISSUE THREAD

**Issue by wenzeslaus** [ncsu-landscape-dynamics/pathways-simulation#97]
Currently, we have this report by Pylint:

```
pathways/consignments.py:507:0: R0914: Too many local variables (20/15) (too-many-locals)
pathways/consignments.py:507:0: R0912: Too many branches (14/12) (too-many-branches)
```

Since there is minimal overlap between the two big branches, it makes sense to move these two branches into separate functions.

**Comment by wenzeslaus** [comment]
@kellynm This will be edits limited to consignments.py. Please assign me if/once I can edit that without stepping on your toes.

**Comment by kellynm** [comment]
You can go ahead. I'm not editing consignments.py right now, other than the aqim_file line we discussed this morning.
